# this file sets configuration options for our jekyll website
title: Jaron Belmore's Personal Website
author: Jaron Belmore
description: This is a web page about Jaron Belmore. 
theme: jekyll-theme-minimal

navbar-links:  
  About me: "https://jabelm20.github.io/Jaron-Belmore/about"